// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class LWWTimestampProto {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LWWTimestampProto {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

utc():bigint {
  return this.bb!.readInt64(this.bb_pos);
}

pid():bigint {
  return this.bb!.readInt64(this.bb_pos + 8);
}

static sizeOf():number {
  return 16;
}

static createLWWTimestampProto(builder:flatbuffers.Builder, utc: bigint, pid: bigint):flatbuffers.Offset {
  builder.prep(8, 16);
  builder.writeInt64(BigInt(pid ?? 0));
  builder.writeInt64(BigInt(utc ?? 0));
  return builder.offset();
}

}
