# Generated by js/config/gen-config.ts. Edit js/config/.env or the template,
# not this file.
#
# Dev TLS reverse proxy. WebCrypto needs a secure context, so the dev stack
# always runs behind Caddy — bare `http://localhost:5176` won't load the app
# from any non-loopback origin (phone over Tailscale/Headscale, etc.).
#
# Override DEV_PROXY_HOSTNAME in js/config/.env to point at your own mesh A
# record. Cert is a wildcard for DEV_PROXY_DOMAIN (auto-derived as the parent
# of DEV_PROXY_HOSTNAME); only DEV_PROXY_HOSTNAME is routed, others 404.
#
# Needs:
#   - CLOUDFLARE_API_TOKEN exported in the shell that runs `process-compose`
#     (Zone:Read + Zone:DNS:Edit scoped to the zone).
#   - A Caddy build with the Cloudflare DNS plugin:
#       xcaddy build --with github.com/caddy-dns/cloudflare
#     or a prebuilt binary from caddyserver.com/download with that plugin.

{
	# Uncomment while iterating to avoid LE prod rate limits (5 dup certs/week).
	# acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
}

*.{{ env "DEV_PROXY_DOMAIN" }} {
	tls {
		dns cloudflare {env.CLOUDFLARE_API_TOKEN}
		resolvers 1.1.1.1
	}

	@airday host {{ env "DEV_PROXY_HOSTNAME" }}
	handle @airday {
		encode zstd gzip

		# Vite dev server. WebSocket upgrades (HMR + /api/sync) pass through
		# transparently; Vite already proxies /api -> :8000 (see js/web/vite.config.ts).
		reverse_proxy localhost:5176 {
			flush_interval -1
		}
	}

	handle {
		respond 404
	}
}
