# Generated by js/config/gen-config.ts. Edit js/config/.env or the template,
# not this file.
#
# Run from the repo root:
#   process-compose -f local/process-compose.yaml

processes:
  wasm:
    command: bun run build:wasm:web
    availability:
      exit_on_end: false

  server:
    command: cargo run -p airday-server
    environment:
      - RUST_LOG={{ env "AIRDAY_LOG_LEVEL" }}
    readiness_probe:
      http_get:
        host: {{ env "AIRDAY_HOST" }}
        port: {{ env "AIRDAY_PORT" }}
        path: /healthz
      initial_delay_seconds: 3
      period_seconds: 2
      failure_threshold: 60

  web:
    command: bun run dev
    working_dir: ./js/web
    depends_on:
      wasm:
        condition: process_completed_successfully
      server:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        port: 5176
        path: /
      initial_delay_seconds: 2
      period_seconds: 2
