# Generated by js/config/gen-config.ts. Edit js/config/.env or the template,
# not this file.
#
# Run from the repo root:
#   process-compose -f local/process-compose.yaml

processes:
  wasm:
    command: bun run build:wasm:web
    availability:
      exit_on_end: false

  server:
    command: cargo run -p airday-server
    environment:
      - RUST_LOG={{ env "AIRDAY_LOG_LEVEL" }}
      - RUST_BACKTRACE=1
    readiness_probe:
      http_get:
        host: {{ env "AIRDAY_HOST" }}
        port: {{ env "AIRDAY_PORT" }}
        path: /healthz
      initial_delay_seconds: 3
      period_seconds: 2
      failure_threshold: 60

  web:
    command: bun run dev -- --host 0.0.0.0
    working_dir: ./js/web
    depends_on:
      wasm:
        condition: process_completed_successfully
      server:
        condition: process_healthy
    readiness_probe:
      http_get:
        host: localhost
        port: 5176
        path: /
      initial_delay_seconds: 2
      period_seconds: 2

  # Reverse proxies https://{{ env "DEV_PROXY_HOSTNAME" }} to the Vite dev
  # server. Reads CLOUDFLARE_API_TOKEN from the shell that invoked
  # process-compose; if unset Caddy will fail the LE DNS-01 challenge.
  caddy:
    command: caddy run --config local/Caddyfile
    depends_on:
      web:
        condition: process_healthy
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
