# Generated by js/config/gen-config.ts. Edit js/config/.env (the deploy
# secrets file at /opt/monoplan/.env on the box) or the template — never
# this file. Installed to /etc/monoplan/server.toml by deploy/ci.sh.

bind = "{{ env "MONOPLAN_BIND" }}"
db = "{{ env "MONOPLAN_DB_PATH" }}"
log_level = "{{ env "MONOPLAN_LOG_LEVEL" }}"
secure_cookies = {{ env "MONOPLAN_SECURE_COOKIES" }}
{{- if env "MONOPLAN_ADMIN_PASSWORD_HASH" }}
admin_password_hash = '{{ env "MONOPLAN_ADMIN_PASSWORD_HASH" }}'
{{- end }}
