# Generated by js/config/gen-config.ts. Edit js/config/.env or the template,
# not this file.

bind = "{{ env "AIRDAY_BIND" }}"
log_level = "{{ env "AIRDAY_LOG_LEVEL" }}"
{{- if env "AIRDAY_DB_PATH" }}
db = "{{ env "AIRDAY_DB_PATH" }}"
{{- end }}
