# Generated by js/config/gen-config.ts. Edit js/config/.env or the template,
# not this file.

bind = "{{ env "MONOPLAN_BIND" }}"
log_level = "{{ env "MONOPLAN_LOG_LEVEL" }}"
# Plain HTTP in dev: Safari drops Secure cookies on http://localhost
# (Chromium/Firefox don't, but we develop on the strictest of the three).
secure_cookies = {{ env "MONOPLAN_SECURE_COOKIES" }}
{{- if env "MONOPLAN_ADMIN_PASSWORD_HASH" }}
admin_password_hash = '{{ env "MONOPLAN_ADMIN_PASSWORD_HASH" }}'
{{- end }}
{{- if env "MONOPLAN_DB_PATH" }}
db = "{{ env "MONOPLAN_DB_PATH" }}"
{{- end }}
