# Generated by js/config/gen-config.ts. Edit js/config/.env (the deploy
# secrets file at /opt/airday/.env on the box) or the template — never
# this file. Installed to /etc/airday/server.toml by deploy/ci.sh.

bind = "{{ env "AIRDAY_BIND" }}"
db = "{{ env "AIRDAY_DB_PATH" }}"
log_level = "{{ env "AIRDAY_LOG_LEVEL" }}"
secure_cookies = {{ env "AIRDAY_SECURE_COOKIES" }}
