// Vendored emoji dataset: schema, lazy loader, group taxonomy.
//
// The dataset is generated by `scripts/vendor-emoji.ts` from
// `emoji-picker-element-data` (Apache-2.0, built from emojibase). We take
// the data only; the search index (`search.ts`) and the picker UI
// (`../EmojiPicker.tsx`) are ours, built on Kobalte primitives.
//
// Loading: imported as `?url` so Vite emits it as a content-hashed asset
// rather than inlining it into a JS chunk — 155kB of object literal is
// slower for the engine to parse than the equivalent `JSON.parse`, and
// keeping it out of the entry bundle means the cost is only paid the
// first time someone opens a picker. The fetch is memoised for the page
// lifetime; the browser HTTP cache (and, once the service worker lands,
// its runtime cache) covers subsequent loads.

import dataUrl from "./emoji-data.json?url";

/** One emoji, decoded from the positional array in the vendored file. */
export interface Emoji {
  /** The literal grapheme, stored verbatim when chosen (`Doc::set_list_icon`). */
  emoji: string;
  /** CLDR short name, e.g. "grinning face". Shown as the preview caption. */
  annotation: string;
  /** Emojibase group id; see `EMOJI_GROUPS`. */
  group: number;
  /** Unicode emoji version that introduced it, used by `support.ts` to hide
   *  emoji this device's fonts can't render. */
  version: number;
  /** Space-joined search keywords. */
  tags: string;
  /** Space-joined `:shortcode:` names (GitHub/Slack style, no colons). */
  shortcodes: string;
}

/** Positional row as written by `scripts/vendor-emoji.ts`. Field order is
 *  mirrored in that file's `fields` key. */
type EmojiRow = [
  emoji: string,
  annotation: string,
  group: number,
  version: number,
  tags: string,
  shortcodes: string,
];

interface EmojiFile {
  source: string;
  fields: string[];
  emoji: EmojiRow[];
}

/** Emojibase group ids in display order. Group 2 (component: skin-tone and
 *  hair modifiers) is stripped at vendoring time and never appears here.
 *  `labelKey` indexes `messages.emoji.groups` — the dataset is English-only,
 *  but the picker chrome around it stays localised. */
export const EMOJI_GROUPS = [
  { id: 0, labelKey: "smileys", icon: "😀" },
  { id: 1, labelKey: "people", icon: "👋" },
  { id: 3, labelKey: "nature", icon: "🐶" },
  { id: 4, labelKey: "food", icon: "🍎" },
  { id: 5, labelKey: "travel", icon: "✈️" },
  { id: 6, labelKey: "activities", icon: "⚽" },
  { id: 7, labelKey: "objects", icon: "💡" },
  { id: 8, labelKey: "symbols", icon: "❤️" },
  { id: 9, labelKey: "flags", icon: "🏳️" },
] as const;

export type EmojiGroupKey = (typeof EMOJI_GROUPS)[number]["labelKey"];

let pending: Promise<Emoji[]> | null = null;

/** Fetch and decode the dataset. Memoised: concurrent callers (two pickers
 *  opened in quick succession) share one request, and the decoded array is
 *  retained for the page lifetime. */
export function loadEmoji(): Promise<Emoji[]> {
  pending ??= fetch(dataUrl)
    .then((res) => {
      if (!res.ok) throw new Error(`emoji data ${res.status}`);
      return res.json() as Promise<EmojiFile>;
    })
    .then((file) =>
      file.emoji.map(
        ([emoji, annotation, group, version, tags, shortcodes]): Emoji => ({
          emoji,
          annotation,
          group,
          version,
          tags,
          shortcodes,
        }),
      ),
    )
    .catch((err: unknown) => {
      // Don't cache the rejection — a transient offline blip shouldn't
      // permanently break the picker for the rest of the session.
      pending = null;
      throw err;
    });
  return pending;
}
