// This is GPT-5 generated semi-slop - bad target
// But is a good reference as it did work for what it did
// TODO: Replace

extern crate proc_macro;
use proc_macro::TokenStream;
use quote::{format_ident, quote, quote_spanned};
use syn::{
    Attribute, Data, DeriveInput, Fields, Ident, LitInt, LitStr, Result, Token,
    parse::{Parse, ParseStream},
    parse_macro_input,
    spanned::Spanned,
};

/// ---------- Struct-level args: #[sync_object(kind_id=..., name="...", base=?)] ----------

#[derive(Default, Clone)]
struct ObjectArgs {
    kind_id: Option<i64>,
    name: Option<String>,
    base: Option<i16>,
}

fn parse_object_args_on(attrs: &[Attribute]) -> Result<ObjectArgs> {
    let mut out = ObjectArgs::default();
    let attr = attrs.iter().find(|a| a.path().is_ident("sync_object"));
    if let Some(attr) = attr {
        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("kind_id") {
                let v: LitInt = meta.value()?.parse()?;
                out.kind_id = Some(v.base10_parse()?);
                return Ok(());
            }
            if meta.path.is_ident("name") {
                let v: LitStr = meta.value()?.parse()?;
                out.name = Some(v.value());
                return Ok(());
            }
            if meta.path.is_ident("base") {
                let v: LitInt = meta.value()?.parse()?;
                out.base = Some(v.base10_parse()?);
                return Ok(());
            }
            // ignore unknown flags for forward-compat
            Ok(())
        })?;
    }
    Ok(out)
}

/// ---------- Field-level args: #[sync_attr(id=..., ty="string" | "i64", borrow?)] ----------

#[derive(Clone)]
struct FieldArgs {
    id: i16,
    ty: String,   // "string" | "i64"
    borrow: bool, // reserved; not used in this v1 LWW-only codegen
}

fn parse_field_args(attrs: &[Attribute]) -> Result<Option<FieldArgs>> {
    for attr in attrs {
        if !attr.path().is_ident("sync_attr") {
            continue;
        }

        let mut id: Option<i16> = None;
        let mut ty: Option<String> = None;
        let mut borrow = false;

        attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("id") {
                let v: LitInt = meta.value()?.parse()?;
                id = Some(v.base10_parse()?);
            } else if meta.path.is_ident("ty") {
                let v: LitStr = meta.value()?.parse()?;
                ty = Some(v.value());
            } else if meta.path.is_ident("borrow") {
                borrow = true;
            }
            Ok(())
        })?;

        let id = id.ok_or_else(|| syn::Error::new(attr.span(), "sync_attr: missing `id`"))?;
        let ty = ty.ok_or_else(|| syn::Error::new(attr.span(), "sync_attr: missing `ty`"))?;
        return Ok(Some(FieldArgs { id, ty, borrow }));
    }
    Ok(None)
}

#[proc_macro_derive(StinkObject, attributes(obj, attr))]
pub fn derive_stink_object(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let ident = input.ident;

    // Generate an inherent method: `fn stink_say_hello(&self)`
    let expanded = quote! {
        impl #ident {
            /// Generated by `#[derive(StinkObject)]` (demo).
            pub fn stink_say_hello(&self) {
                println!("Hello from StinkObject on {}", stringify!(#ident));
            }
        }
    };

    TokenStream::from(expanded)
}

/// ---------- The main derive: generates consts + SyncKind + AttrCodec ----------
#[proc_macro_derive(SyncObject, attributes(sync_object, sync_attr))]
pub fn derive_sync_object(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);

    let struct_ident = input.ident.clone();
    let Data::Struct(ds) = &input.data else {
        return syn::Error::new(input.span(), "#[derive(SyncObject)] only on structs")
            .to_compile_error()
            .into();
    };

    // Parse struct-level args
    let args = match parse_object_args_on(&input.attrs) {
        Ok(v) => v,
        Err(e) => return e.to_compile_error().into(),
    };
    let kind_id = match args.kind_id {
        Some(v) => v,
        None => {
            return syn::Error::new(
                struct_ident.span(),
                "missing `#[sync_object(kind_id = ...)]`",
            )
            .to_compile_error()
            .into();
        }
    };
    let name = args.name.unwrap_or_else(|| struct_ident.to_string());

    // Named fields only
    let Fields::Named(named) = &ds.fields else {
        return syn::Error::new(ds.struct_token.span, "named fields required")
            .to_compile_error()
            .into();
    };

    // Collect fields that have #[sync_attr(...)]
    let mut field_infos: Vec<(Ident, syn::Type, FieldArgs)> = vec![];
    let mut seen = std::collections::BTreeSet::<i16>::new();

    for f in &named.named {
        let fa = match parse_field_args(&f.attrs) {
            Ok(Some(fa)) => fa,
            Ok(None) => continue,
            Err(e) => return e.to_compile_error().into(),
        };
        if !seen.insert(fa.id) {
            return syn::Error::new_spanned(&f, format!("duplicate field id {}", fa.id))
                .to_compile_error()
                .into();
        }
        field_infos.push((f.ident.clone().unwrap(), f.ty.clone(), fa));
    }

    // ---------- Codegen pieces ----------

    // 1) Associated consts: <Struct>::STRUCT_FIELD
    let consts = field_infos.iter().map(|(ident, _ty, fa)| {
        let const_ident = format_ident!(
            "{}_{}",
            struct_ident.to_string().to_uppercase(),
            ident.to_string().to_uppercase()
        );
        let id = fa.id;
        quote! { pub const #const_ident: i16 = #id; }
    });

    // A helper to refer to the associated const with full path (#struct_ident::CONST)
    let const_paths = field_infos
        .iter()
        .map(|(ident, _ty, _fa)| {
            let const_ident = format_ident!(
                "{}_{}",
                struct_ident.to_string().to_uppercase(),
                ident.to_string().to_uppercase()
            );
            quote! { #struct_ident::#const_ident }
        })
        .collect::<Vec<_>>();

    // 2) encode arms (LWW only, string & i64)
    let enc_arms = field_infos.iter().zip(const_paths.iter()).map(|((ident, _ty, fa), const_path)| {
        match fa.ty.as_str() {
            "string" => quote! {
                if let Some(val) = &self.#ident {
                    let ts = proto::LWWTimestampProto::new(val.timestamp.utc, val.timestamp.pid);
                    let s  = fbb.create_string(&val.data);
                    let attr = proto::AttributeProto::create(
                        fbb,
                        &proto::AttributeProtoArgs{
                            field_id: #const_path,
                            value_type: proto::AttrTypeProto::STRING,
                            timestamp: Some(&ts),
                            string: Some(s),
                            bytes: None,
                            i64_fb: 0,
                            f64_fb: 0.0,
                        }
                    );
                    out.push(attr);
                }
            },
            "i64" => quote! {
                if let Some(val) = &self.#ident {
                    let ts = proto::LWWTimestampProto::new(val.timestamp.utc, val.timestamp.pid);
                    let attr = proto::AttributeProto::create(
                        fbb,
                        &proto::AttributeProtoArgs{
                            field_id: #const_path,
                            value_type: proto::AttrTypeProto::I64,
                            timestamp: Some(&ts),
                            string: None,
                            bytes: None,
                            i64_fb: val.data,
                            f64_fb: 0.0,
                        }
                    );
                    out.push(attr);
                }
            },
            other => quote_spanned! { ident.span()=>
                compile_error!(concat!("unsupported ty for LWW: ", #other, " (expected \"string\" | \"i64\")"));
            }
        }
    });

    // 3) decode init -> None for each Option<...>
    let dec_init_fields = field_infos.iter().map(|(ident, _ty, _fa)| {
        quote! { #ident: None }
    });

    // 4) decode arms
    let dec_arms = field_infos.iter().zip(const_paths.iter()).map(|((ident, _ty, fa), const_path)| {
        match fa.ty.as_str() {
            "string" => quote! {
                #const_path => {
                    if a.value_type() == proto::AttrTypeProto::STRING {
                        if let (Some(ts), Some(sv)) = (a.timestamp(), a.string()) {
                            s.#ident = Some(::crdt::LWWRegister {
                                timestamp: ::crdt::timestamp::LWWTimestamp { utc: ts.utc(), pid: ts.pid() },
                                data: sv.to_string(),
                            });
                        }
                    }
                }
            },
            "i64" => quote! {
                #const_path => {
                    if a.value_type() == proto::AttrTypeProto::I64 {
                        if let Some(ts) = a.timestamp() {
                            s.#ident = Some(::crdt::LWWRegister {
                                timestamp: ::crdt::timestamp::LWWTimestamp { utc: ts.utc(), pid: ts.pid() },
                                data: a.i64_fb(),
                            });
                        }
                    }
                }
            },
            _ => quote_spanned! { ident.span()=> {} }
        }
    });

    // 5) merge arms (LWW)
    let merge_arms = field_infos
        .iter()
        .map(|(ident, _ty, fa)| match fa.ty.as_str() {
            "string" | "i64" => quote! {
                if let Some(other_v) = &other.#ident {
                    if let Some(me) = &self.#ident {
                        let a = me.clone();
                        let b = other_v.clone();
                        self.#ident = Some(a.merge(b));
                    } else {
                        self.#ident = Some(other_v.clone());
                    }
                }
            },
            _ => quote_spanned! { ident.span()=> {} },
        });

    // 6) Put it all together
    let out = quote! {
        // Associated constants for field ids
        impl #struct_ident {
            #(#consts)*
        }

        impl crate::sync_engine::engine::SyncKind for #struct_ident {
            const KIND_ID: i64 = #kind_id;
            const NAME: &'static str = #name;
        }

        impl crate::sync_engine::engine::AttrCodec for #struct_ident {
            fn encode_attrs(
                &self,
                fbb: &mut flatbuffers::FlatBufferBuilder<'_>,
                out: &mut Vec<flatbuffers::WIPOffset<crate::sync_transport::proto_generated::proto::AttributeProto<'_>>>,
            ) {
                use crate::sync_transport::proto_generated::proto as proto;
                #(#enc_arms)*
            }

            fn decode_attrs(attr_set: &crate::sync_transport::proto_generated::proto::AttributeSetProto<'_>) -> Self {
                use crate::sync_transport::proto_generated::proto as proto;
                let mut s = Self { #(#dec_init_fields),* };
                if let Some(attrs) = attr_set.attributes() {
                    for i in 0..attrs.len() {
                        let a = attrs.get(i);
                        match a.field_id() {
                            #(#dec_arms)*
                            _ => {}
                        }
                    }
                }
                s
            }

            fn merge_into(&mut self, other: &Self) {
                #(#merge_arms)*
            }
        }
    };

    out.into()
}

/// ---------- Optional: super-enum builder ----------
struct IdentList(syn::punctuated::Punctuated<Ident, Token![,]>);

impl Parse for IdentList {
    fn parse(input: ParseStream) -> Result<Self> {
        Ok(Self(syn::punctuated::Punctuated::parse_terminated(input)?))
    }
}

#[proc_macro]
pub fn sync_objects(input: TokenStream) -> TokenStream {
    let list = parse_macro_input!(input as IdentList).0;
    let idents: Vec<Ident> = list.into_iter().collect();

    let enum_variants = idents.iter().map(|id| quote! { #id(#id) });

    let kind_id_match = idents.iter().map(|id| {
        quote! {
            SyncObjectAttrs::#id(_) => <#id as crate::sync_engine::engine::SyncKind>::KIND_ID
        }
    });

    let encode_match = idents.iter().map(|id| {
        quote! {
            SyncObjectAttrs::#id(v) => {
                use crate::sync_transport::proto_generated::proto as proto;
                let mut fbb = flatbuffers::FlatBufferBuilder::new();
                let mut vec_attrs = Vec::new();
                v.encode_attrs(&mut fbb, &mut vec_attrs);
                if vec_attrs.is_empty() { return None; }
                let attrs_vec = fbb.create_vector(&vec_attrs);
                let set = proto::AttributeSetProto::create(&mut fbb, &proto::AttributeSetProtoArgs{
                    attributes: Some(attrs_vec)
                });
                fbb.finish(set, None);
                Some(fbb.finished_data().to_vec())
            }
        }
    });

    let merge_match = idents.iter().map(|id| {
        quote! {
            (SyncObjectAttrs::#id(a), SyncObjectAttrs::#id(b)) => { a.merge_into(b); Ok(()) }
        }
    });

    let decode_if = idents.iter().map(|id| quote! {
        if kind_id == <#id as crate::sync_engine::engine::SyncKind>::KIND_ID {
            let set = flatbuffers::root::<crate::sync::proto_generated::proto::AttributeSetProto>(blob).ok()?;
            let v = <#id as crate::sync_engine::engine::AttrCodec>::decode_attrs(&set);
            return Some(SyncObjectAttrs::#id(v));
        }
    });

    let out = quote! {
        #[derive(Debug, Clone)]
        pub enum SyncObjectAttrs { #( #enum_variants ),* }

        impl SyncObjectAttrs {
            pub fn kind_id(&self) -> i64 {
                match self { #( #kind_id_match ),* }
            }
            pub fn encode_blob(&self) -> Option<Vec<u8>> {
                match self { #( #encode_match ),* }
            }
            pub fn decode(kind_id: i64, blob: &[u8]) -> Option<Self> {
                #( #decode_if )*
                None
            }
            pub fn merge(&mut self, other: &Self) -> ::std::result::Result<(), crate::common::error::AppError> {
                match (self, other) {
                    #( #merge_match ),*,
                    _ => Err(crate::common::error::AppError::ValidationError("wrong variant on merge".into())),
                }
            }
        }
    };
    out.into()
}
