# ░▒█ Server settings
host = "0.0.0.0"
port = 3000
secure_cookies = false

# ░▒█ Dummy keys (replace w gen_paseto_keys output)
paseto_pk = "k4.public.-DMh5-pWig7tBJmLeGgAitVuidtNnmsoAOmciFzEsQE"
paseto_sk = "k4.secret.7zh6sBjSL5wpIUkrqry8x_UyyxqZ_PJyaDB_GoMG-Q74MyHn6laKDu0EmYt4aACK1W6J202eaygA6ZyIXMSxAQ"

# ░▒█ Database settings
sqlx_host = "sqlite:$HOME/.config/airday/airday.db"

# ░▒█ Telemetry
log_level = "debug"
# otlp_host = "http://localhost:4318/v1/traces"

# ░▒█ Server features
# Allow new sign ups on this instance
# allow_create_user = false
