# ░▒█ Server settings
host = "0.0.0.0"
port = 3000
secure_cookies = false

# ░▒█ Dummy keys (replace w gen_paseto_keys output)
paseto_pk = zzBHKWbOVoE7HTijocAzekDfPM2JTvIFmFyZ4kYtVLs=
paseto_sk = mpHLwtGPobLDlvSJuLpxf4L1vX78vMWleF/0pVs+pkTPMEcpZs5WgTsdOKOhwDN6QN88zYlO8gWYXJniRi1Uuw==

# ░▒█ Database settings
sqlx_host = "sqlite:$HOME/.config/airday/airday.db"

# ░▒█ Telemetry
log_level = "debug"
# otlp_host = "http://localhost:4318/v1/traces"

# ░▒█ Server features
# Allow new sign ups on this instance
# allow_create_user = false
